feat: add now deploy nodeJs in Vercel.
lucas-felinto/readme_maker pull request #35
Opened 2022-12-20 20:29 UTC by robsonamendonca

2022-12-20 20:50 UTC, lucas-felinto requested changes

2022-12-20 20:50 UTC, lucas-felinto commented on README.md
> +| [<img src="https://avatars1.githubusercontent.com/u/57813174?s=460&u=b945fd8ddf70b205101773a7ab47b1a07576af7c&v=4" width=115><br><sub>Wemerson Jesus</sub>](https://github.com/wejesuss) | [<img src=
fix Collaborators session

2022-12-21 03:27 UTC, robsonamendonca commented on README.md
> +| [<img src="https://avatars1.githubusercontent.com/u/57813174?s=460&u=b945fd8ddf70b205101773a7ab47b1a07576af7c&v=4" width=115><br><sub>Wemerson Jesus</sub>](https://github.com/wejesuss) | [<img src=
ok

2022-12-21 03:40 UTC, closed without merging

2022-12-21 03:40 UTC, robsonamendonca commented
revisão para evitar conflito.